### PR TITLE
Use ids

### PR DESCRIPTION
**Pull request by alanfischer**
Use category ids instead of names

### CODE REVIEW

**Comment by pavoni** [comment]
Will merge this now so we can test.

There is still a little `category_name` logic left which we should think through - both for queries (don't know how much this is used) and for Armable sensors.

**Comment by pavoni** [comment]
Should be available as `0.2.36a0` although I tried to call it `0.2.36alpha`

Worth checking if this works for you.

**Comment by alanfischer** [comment]
@pavoni Do you have armable sensors to test with?  I don't own any so I'm not exactly sure what changes should be made to have them behave correctly.

**Comment by pavoni** [comment]
I do have one (although I don't use the arming).

I'll take a look.

**Pull request merged**
