### PR TITLE
Add power consumption.

### PR DESCRIPTION
**Pull request by pavoni**
Add power consumption property.

### CODE REVIEW

**Comment by snizzleorg** [comment]
how this should show up in home-assistant? as an additional sensor?

**Comment by pavoni** [comment]
@snizzleorg Afraid I'm not in the same location as my Vera - won't be there until next week, so can't test.

This PR will add the power attribute to existing HA switches. You should see it as an additional attribute. https://github.com/home-assistant/home-assistant/pull/2490

You can break it out as a dedicated sensor if you want to using a sensor template.

I don't know if there are other devices that also support the power attribute.

**Comment by snizzleorg** [comment]
hm. for mine it doesn't yet show up as additional property. This is with hass 0.23.1...not sure if the commit is already included in hass 0.23.1

**Comment by pavoni** [comment]
The PR isn't merged! You can try my test branch if you run a dev build.

Can't merge until it's been tested!

**Comment by snizzleorg** [comment]
shit. I can't test that easy since im running a docker image.

**Pull request merged**
