### PR TITLE
Handle comm failure status being None.

### LINKED ISSUE #145: comm_failure method incorrectly returns True when CommFailure variable not present in Vera response
Problem:
For devices which have never had a communication failure, the VeraDevice comm_failure method incorrectly returns True when the device is communicating.  This is due to the 'CommFailure' variable not being present in the device info returned by Vera.

It appears that my Vera Edge does not include the CommFailure variable in the device info that it returns until there has been a communication failure.  At this point, the CommFailure variable starts appearing in responses, with a value of '1'.  After communication returns to normal, it continues to include the CommFailure variable in reponses, with a value of '0'.

If the response does not include the CommFailure variable, the comm_failure method incorrectly returns True since the variable is not equal to '1':

```
    @property
    def comm_failure(self) -> bool:
        """Return the Communication Failure Flag."""
        return cast(str, self.get_strict_value("commFailure")) != "0"
```

I tried modifying the method to check for the existence of the value first, it it performs as expected:

```
    @property
    def comm_failure(self) -> bool:
        """Return the Communication Failure Flag."""
        flag = self.get_strict_value("commFailure")
        if flag is not None:
            return cast(str, flag) != "0"
        else:
            return False
```

Further detail:
Vera Edge controller firmware version:  1.7.5185 (7.31)
Device under test: Leviton DZ15S

Example response from a device which has not experienced a communication failure:
```
			"states": [
				{
					"service": "urn:micasaverde-com:serviceId:ZWaveDevice1",
					"variable": "Capabilities",
					"value": "211,156,1,4,16,1,L,R,B,RS,|32,37,39,43,44,89,90,94,112,114,115,122,133,134,",
					"id": 0
				},
				{
					"service": "urn:micasaverde-com:serviceId:ZWaveDevice1",
					"variable": "PollSettings",
					"value": "0",
					"id": 1
				},
				{
					"service": "urn:micasaverde-com:serviceId:ZWaveDevice1",
					"variable": "ManufacturerInfo",
					"value": "29,13313,1",
					"id": 2
				},
				{
					"service": "urn:micasaverde-com:serviceId:ZWaveDevice1",
					"variable": "VersionInfo",
					"value": "3,4,33,1,20",
					"id": 3
				},
				{
					"service": "urn:micasaverde-com:serviceId:ZWaveDevice1",
					"variable": "VariablesSet",
					"value": "7-Locator LED Status (0=LED or 254=Status Mode or 255=Locator Mode),1d,",
					"pnp": "*1.7.5185*",
					"id": 4
				},
				{
					"service": "urn:micasaverde-com:serviceId:HaDevice1",
					"variable": "Configured",
					"value": "1",
					"id": 5
				},
				{
					"service": "urn:micasaverde-com:serviceId:ZWaveDevice1",
					"variable": "NodeInfo",
					"value": "20,25,27,2b,2c,59,5a,5e,70,72,73,7a,85,86,",
					"id": 6
				},
				{
					"service": "urn:micasaverde-com:serviceId:ZWaveDevice1",
					"variable": "PlusInfo",
					"value": "1,5,0,7,0,7,0",
					"id": 7
				},
				{
					"service": "urn:micasaverde-com:serviceId:ZWaveDevice1",
					"variable": "FirmwareInfo",
					"value": "29,257,23255",
					"id": 8
				},
				{
					"service": "urn:micasaverde-com:serviceId:ZWaveDevice1",
					"variable": "AgiInfo",
					"value": "X",
					"id": 9
				},
				{
					"service": "urn:micasaverde-com:serviceId:ZWaveDevice1",
					"variable": "ConfiguredAssoc",
					"value": "",
					"id": 10
				},
				{
					"service": "urn:micasaverde-com:serviceId:ZWaveDevice1",
					"variable": "VariablesGet",
					"value": "7,255,",
					"id": 11
				},
				{
					"service": "urn:micasaverde-com:serviceId:ZWaveDevice1",
					"variable": "ConfiguredVariable",
					"value": "7-Locator LED Status (0=LED or 254=Status Mode or 255=Locator Mode),1d,",
					"id": 12
				},
				{
					"service": "urn:micasaverde-com:serviceId:HaDevice1",
					"variable": "ModeSetting",
					"value": "1:;2:;3:;4:",
					"id": 13
				},
				{
					"service": "urn:micasaverde-com:serviceId:HaDevice1",
					"variable": "LastUpdate",
					"value": "1610911045",
					"id": 14
				},
				{
					"service": "urn:micasaverde-com:serviceId:HaDevice1",
					"variable": "FirstConfigured",
					"value": "1610911045",
					"id": 15
				},
				{
					"service": "urn:micasaverde-com:serviceId:ZWaveDevice1",
					"variable": "Neighbors",
					"value": "",
					"id": 16
				},
				{
					"service": "urn:micasaverde-com:serviceId:ZWaveDevice1",
					"variable": "LastReset",
					"value": "1610911044",
					"id": 17
				},
				{
					"service": "urn:micasaverde-com:serviceId:ZWaveDevice1",
					"variable": "AssociationNum",
					"value": "1",
					"id": 18
				},
				{
					"service": "urn:upnp-org:serviceId:SwitchPower1",
					"variable": "Status",
					"id": 19,
					"value": "0"
				},
				{
					"service": "urn:micasaverde-com:serviceId:ZWaveDevice1",
					"variable": "PollOk",
					"id": 20,
					"value": "53"
				},
				{
					"service": "urn:micasaverde-com:serviceId:HaDevice1",
					"variable": "PollRatings",
					"id": 21,
					"value": "4.90"
				},
				{
					"service": "urn:micasaverde-com:serviceId:ZWaveNetwork1",
					"variable": "LastPollSuccess",
					"id": 22,
					"value": "1611982800"
				},
				{
					"service": "urn:micasaverde-com:serviceId:ZWaveNetwork1",
					"variable": "ConsecutivePollFails",
					"id": 23,
					"value": "0"
				},
				{
					"service": "urn:micasaverde-com:serviceId:ZWaveDevice1",
					"variable": "LastRouteUpdate",
					"value": "1610911105",
					"id": 24
				},
				{
					"service": "urn:upnp-org:serviceId:SwitchPower1",
					"variable": "Target",
					"id": 25,
					"value": "0"
				},
				{
					"service": "urn:micasaverde-com:serviceId:HaDevice1",
					"variable": "sl_Hail",
					"id": 26,
					"value": "1"
				},
				{
					"id": 167,
					"service": "urn:micasaverde-com:serviceId:ZWaveDevice1",
					"variable": "LastNnu",
					"value": "1611910800,8"
				},
				{
					"id": 169,
					"service": "urn:micasaverde-com:serviceId:ZWaveDevice1",
					"variable": "LastArr",
					"value": "1611910800,8"
				},
				{
					"id": 85,
					"service": "urn:micasaverde-com:serviceId:ZWaveDevice1",
					"variable": "PollNoReply",
					"value": "1"
				}
			],
```

Example response from a device which has previously experienced a communication failure and has returned to normal:

```
			"states": [
				{
					"service": "urn:micasaverde-com:serviceId:ZWaveDevice1",
					"variable": "Capabilities",
					"value": "211,156,1,4,16,1,L,R,B,RS,|32,37,39,43,44,89,90,94,112,114,115,122,133,134,",
					"id": 0
				},
				{
					"service": "urn:micasaverde-com:serviceId:ZWaveDevice1",
					"variable": "PollSettings",
					"value": "0",
					"id": 1
				},
				{
					"service": "urn:micasaverde-com:serviceId:ZWaveDevice1",
					"variable": "ManufacturerInfo",
					"value": "29,13313,1",
					"id": 2
				},
				{
					"service": "urn:micasaverde-com:serviceId:ZWaveDevice1",
					"variable": "VersionInfo",
					"value": "3,4,33,1,20",
					"id": 3
				},
				{
					"service": "urn:micasaverde-com:serviceId:ZWaveDevice1",
					"variable": "VariablesSet",
					"value": "7-Locator LED Status (0=LED or 254=Status Mode or 255=Locator Mode),1d,",
					"pnp": "*1.7.5185*",
					"id": 4
				},
				{
					"service": "urn:micasaverde-com:serviceId:HaDevice1",
					"variable": "Configured",
					"value": "1",
					"id": 5
				},
				{
					"service": "urn:micasaverde-com:serviceId:ZWaveDevice1",
					"variable": "NodeInfo",
					"value": "20,25,27,2b,2c,59,5a,5e,70,72,73,7a,85,86,",
					"id": 6
				},
				{
					"service": "urn:micasaverde-com:serviceId:ZWaveDevice1",
					"variable": "PlusInfo",
					"value": "1,5,0,7,0,7,0",
					"id": 7
				},
				{
					"service": "urn:micasaverde-com:serviceId:ZWaveDevice1",
					"variable": "FirmwareInfo",
					"value": "29,257,23255",
					"id": 8
				},
				{
					"service": "urn:micasaverde-com:serviceId:ZWaveDevice1",
					"variable": "AgiInfo",
					"value": "X",
					"id": 9
				},
				{
					"service": "urn:micasaverde-com:serviceId:ZWaveDevice1",
					"variable": "ConfiguredAssoc",
					"value": "",
					"id": 10
				},
				{
					"service": "urn:micasaverde-com:serviceId:ZWaveDevice1",
					"variable": "VariablesGet",
					"value": "7,255,",
					"id": 11
				},
				{
					"service": "urn:micasaverde-com:serviceId:ZWaveDevice1",
					"variable": "ConfiguredVariable",
					"value": "7-Locator LED Status (0=LED or 254=Status Mode or 255=Locator Mode),1d,",
					"id": 12
				},
				{
					"service": "urn:micasaverde-com:serviceId:HaDevice1",
					"variable": "ModeSetting",
					"value": "1:;2:;3:;4:",
					"id": 13
				},
				{
					"service": "urn:micasaverde-com:serviceId:HaDevice1",
					"variable": "LastUpdate",
					"value": "1610911208",
					"id": 14
				},
				{
					"service": "urn:micasaverde-com:serviceId:HaDevice1",
					"variable": "FirstConfigured",
					"value": "1610911208",
					"id": 15
				},
				{
					"service": "urn:micasaverde-com:serviceId:ZWaveDevice1",
					"variable": "Neighbors",
					"value": "",
					"id": 16
				},
				{
					"service": "urn:micasaverde-com:serviceId:ZWaveDevice1",
					"variable": "LastReset",
					"value": "1610911206",
					"id": 17
				},
				{
					"service": "urn:micasaverde-com:serviceId:ZWaveDevice1",
					"variable": "AssociationNum",
					"value": "1",
					"id": 18
				},
				{
					"service": "urn:upnp-org:serviceId:SwitchPower1",
					"variable": "Status",
					"id": 19,
					"value": "0"
				},
				{
					"service": "urn:micasaverde-com:serviceId:ZWaveDevice1",
					"variable": "PollOk",
					"id": 20,
					"value": "25"
				},
				{
					"service": "urn:micasaverde-com:serviceId:HaDevice1",
					"variable": "PollRatings",
					"value": "5.00",
					"id": 21
				},
				{
					"service": "urn:micasaverde-com:serviceId:ZWaveNetwork1",
					"variable": "LastPollSuccess",
					"id": 22,
					"value": "1611349099"
				},
				{
					"service": "urn:micasaverde-com:serviceId:ZWaveNetwork1",
					"variable": "ConsecutivePollFails",
					"value": "0",
					"id": 23
				},
				{
					"service": "urn:upnp-org:serviceId:SwitchPower1",
					"variable": "Target",
					"id": 24,
					"value": "0"
				},
				{
					"service": "urn:micasaverde-com:serviceId:HaDevice1",
					"variable": "sl_Hail",
					"id": 25,
					"value": "1"
				},
				{
					"id": 131,
					"service": "urn:micasaverde-com:serviceId:ZWaveDevice1",
					"variable": "LastNnu",
					"value": "1611910800,8"
				},
				{
					"id": 133,
					"service": "urn:micasaverde-com:serviceId:ZWaveDevice1",
					"variable": "LastArr",
					"value": "1611910800,8"
				},
				{
					"id": 256,
					"service": "urn:micasaverde-com:serviceId:HaDevice1",
					"variable": "CommFailure",
					"value": "0"
				},
				{
					"id": 1,
					"service": "urn:micasaverde-com:serviceId:HaDevice1",
					"variable": "CommFailureTime",
					"value": "0"
				},
				{
					"id": 36,
					"service": "urn:micasaverde-com:serviceId:HaDevice1",
					"variable": "CommFailureAlarm",
					"value": "1611349097,0"
				}
			],

```

### PR DESCRIPTION
**Pull request by pavoni**
Fixes #145

### CODE REVIEW

**Review by tgrusendorf — APPROVED** [review]
Tested and passed the following cases:
1. device with CommFailure variable not present in response from Vera - returns False
2. device with CommFailure variable = '1' in response from Vera - returns True
3. device with CommFailure variable = '0' in response from Vera - returns False

**Comment by pavoni** [comment]
Thanks.

Are you using this in Home Assistant?

If so I'll try and get this in the next release. They've started the new beta - but they're usually happy to drop in bug fixes.

**Comment by tgrusendorf** [comment]
Yes, I am using it with Home Assistant.  I'm working on getting devices with a comm failure to show 'Unavailable', in particular so that I can generate notifications when things such as my flood sensor are offline.  

I have two more hurdles so far:

1. After a comm failure returns to normal, the Vera subscription does not always report the state returning to -1, so often the last subscription update I get for the device shows state 1 with comm failure = 0.  It looks like you've encountered a similar issue with locks not returning state to -1, so I'm using your lock workaround for all devices at the moment.  Requesting a complete update from Vera does show that the state has returned to -1.  I'm planning to add another issue for this, it probably needs some discussion.

2. Once a device is in comm failure, Vera doesn't necessarily continue trying it.  For my flood sensor it does, so it will return to normal on its own.  For my dimmers it does not, so I have to ask Vera to poll the device.  I'm considering adding a 'Poll Device' service to the Vera integration so that I can trigger a poll from HA.  Would you consider adding periodic polling of devices with comm failure to pyvera?

Do you maintain the HA integration too?

**Comment by pavoni** [comment]
Sounds like it's worth holding off on the HA release until we've covered the issue more completely.

I'd also love my HA devices to properly handle comm failure!

I've done some work on the HA integration - although until the last week when I fixed a problem with initial states I hadn't done anything since @vangorra re-wrote and upgraded it. So I'm not 100% up to speed.

I'm pretty sure @vangorra modified the HA integration so that the HA devices poll as well as responding to subscription updates (HA objects poll by default unless you tell them not to - and he just removed my code that turned this off). 

The catch is they poll the pyvera device - which returns cached values (unless you pass `refresh=true` to get the status from the real device).

But you can perhaps force a refresh in the HA integration if the device is in comm failure?

Would also be happy for you to add a `poll_device` call to `VeraDevice`. Again you could call this from HA if needed.

I think @vangorra is busy with other things - but he might have a few moments to comment.

Added as an issue here: https://github.com/pavoni/pyvera/issues/147

**Pull request merged**
