### PR TITLE
Added scene support

### PR DESCRIPTION
**Pull request by alanfischer**
This adds scene support

### CODE REVIEW

**Comment by alanfischer** [comment]
Closing this for now, I realized I need to expose a couple other items for a clean home-assistant integration...

**Comment by alanfischer** [comment]
Ok, this should be better...

**Comment by pavoni** [comment]
Looks good - duplicates some of the `VeraDevice` methods. What was the reason you decided to duplicate rather than inherit?

**Comment by alanfischer** [comment]
The api exposes the scenes separately from the devices:  {"scenes":[{...},...], "devices":[{...},...]}
And the scene ids are a separate set than the device ids, so scene ids overlap with device ids.
If you would prefer I can certainly still use the VeraDevice & device_id members in there to store the scene items.

**Comment by alanfischer** [comment]
Ok, added some comments related to these

**Comment by pavoni** [comment]
Thanks for this - now released as `0.2.39`

**Pull request merged**
