### PR TITLE
Add ability for HASS to determine when user enters a valid PIN on lock

### PR DESCRIPTION
**Pull request by colohan**
I really wanted Home Assistant to be able to take an action when I unlock my door with a valid PIN.  But the pyvera library didn't seem to give me the ability to do that in a clean way (and honestly, the Vera HTTP API makes it crazily complex to detect this event....).

So I created a function which makes this information to Home Assistant.  I also added a bunch of comments clarifying what I learned as I read the code.  Please let me know if you'd like anything here changed!

### CODE REVIEW

**Comment by pavoni** [comment]
This looks good to me - and thanks for taking the time to add the very useful comments.
Any thoughts from elsewhere before I merge?

**Comment by colohan** [comment]
FYI -- the corresponding PR for Home Assistant (plumbing this through) is here:  https://github.com/home-assistant/home-assistant/pull/27043

**Comment by pavoni** [comment]
Now released as 0.3.6. Thanks for the contribution.

**Comment by colohan** [comment]
Thanks for making it easy to contribute!  ;-)

**Pull request merged**
